### ISSUE TITLE
how can Devre v3.0 NN be so strong ?

### ISSUE THREAD

**Issue by tissatussa** [OmerFarukTutkun/Devre#9]
it's amazing to see Devre having a rating of 3222 on CCRL .. you write "The default net was trained with 1 billion positions from Leela data" .. the binary is only 2.1 Mb, i wonder what you did to achieve that (i'm not a programmer of any engine, just a user).

is Devre v3.0 a hybrid engine, using both normal evaluation and the NN ?
and can you tell what kind of Leela positions where used for the "training" ?

**Comment by OmerFarukTutkun** [comment]
I don't have any classical eval. I'm just using NNUE. Bigger networks are better maybe +30 +40 elo, I don't know. I am using small NNUE because they are faster to train. I'm gonna train bigger networks soon: 12 or 24 Mb.

Leela data: http://trainingdata.farseer.org/ generated by Farseer. I don't know exactly how these data/games are generated, I just use it. I filter positions where the best move is capture or king is in check to get quiet positions so that NNUE will learn easier.

**Comment by tissatussa** [comment]
thanks for the feedback .. you gave good info and i think i understand .. so, you just filter a huge set of games instead of classical evaluation?

interesting .. when adjusting your flter, how does it matter? do you develop new Devre versions like this? You write that you're not using classical eval, but your README states many search functions .. what's the connection with the NN part ?

**Comment by OmerFarukTutkun** [comment]
I'm not doing anything special, what I'm doing is the same as other engines:)

Classical Eval/ hand-crafted evaluation (HCE): It means the evaluation terms are written by hand like piece values, king safety, opposite color bishop bonus, passed pawn bonus, double pawn penalty, mobility, etc. I'm not using HCE I'm using a neural network. To train neural networks millions of positions are needed but not all positions are good for training.
 For example, rnb1kbnr/ppp1pppp/8/8/8/5q2/PPPP1PPP/RNB1KBNR w KQkq - 0 4 the position will be equal after Nxf3 but the neural network cannot understand this because white is queen down right now. So, these kinds of positions are removed from the dataset to make the training process better. It is the search's job to find Nxf3 after calculation, not the neural network.

NNUE's job is to assign a score to a position, and the search's job is to calculate lines and find the best one. So, they can be considered separately, there is not much connection between them.

**Comment by tissatussa** [comment]
are you a (good) chess player yourself? Do you understand when i say : "train the engine to use the f-pawn" and feed many positions according this, including Kings Gambit as opening, but also middle- and end-games ? I guess then Leela plays many (fast) games against itself with concerning starting positions ?

**Comment by OmerFarukTutkun** [comment]
https://lichess.org/@/OmerFarukTutkun

NNUE is a black box. I'm not sure it is possible to train NNUE that will adopt a style.    

>  I guess then Leela plays many (fast) games against itself with concerning starting positions? 

Yes.

**Comment by tissatussa** [comment]
OK .. when i say "the f-pawn", this is not related to style .. it's more about learning the character of the f-pawn related to the other pawns, eg. especially when White castled queenside (then freely use the f-pawn to attack) or kingside (keep the f-pawn on f2 to defend) -- generally spreaking.

can do an experiment ? how long does it take to train such NN ? when we feed many f-pawn related positions to Leela, will it play better in Kings Gambit games, and..: how will it play other openings with such NN ? Do you setup tournaments with several engines / versions to judge their strength ?  My rating is about 1850 in club play, 2050 at LiChess (only Rapid).  Maybe i can supply such starting position - i have to think and dig a little ..

**Comment by tissatussa** [comment]
i found you : https://lichess.org/3SxmHZja/black .. replaying your game, i thought 22...Rxg2+! but you played Nf4 .. nevermind, nice chess !

**Comment by OmerFarukTutkun** [comment]
Sorry, but I cannot do an experiment. That wouldn't work at all. Even making NNUE learn piece values is not easy, what you are saying is very complex.  

Leela-like neural nets might be better to look at, for example, https://lichess.org/@/maia9 is trained with human games and can play like a human.

**Comment by tissatussa** [comment]
thanks for the info .. i played the maia9 bot on LiChess and made a positive score .. what i said is complex? well, i'm not into NN training yet, i view things from another perspective i guess, nevermind ..

once i was also thinking about (all) positions in the variation tree which end when no (more) captures can be done .. it's a special perft routine ! I searched for a linux binary or (python) script which does this, regardless its speed .. do you know? and can you point me to a source?

**Comment by OmerFarukTutkun** [comment]
I don't know such a program but probably  somebody has done what you are asking

**Comment by tissatussa** [comment]
OK, i thought you might know some source.
i guess we can close this issue now.
